# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dlf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='parent_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dlf_app.Place'),
        ),
    ]
